{
 "title": "Druid Connection Pool Dashboard",
 "description": "Alibaba Druid Connection Pool Monitoring via Promethus & SpringBoot Actuator & Micrometer",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(druid_initial_size{application=\"$application\"}, instance)"
   },
   {
    "name": "pool",
    "label": "Connection Pool",
    "query": "label_values(druid_initial_size{application=\"$application\"}, pool)"
   }
  ]
 },
 "panels": [
  { "title": "Connection Pool Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Initial Pool Size",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_initial_size{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"})"
    }
   ]
  },
  {
   "title": "Min Idle Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_min_idle{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"})"
    }
   ]
  },
  {
   "title": "Max Active Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_max_active{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"})"
    }
   ]
  },
  {
   "title": "Peak Pooling Connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(druid_pooling_peak{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"})"
    }
   ]
  },
  {
   "title": "Peak Active Connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(druid_active_peak{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"})"
    }
   ]
  },
  {
   "title": "Wait Thread Connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(druid_wait_thread_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"})"
    }
   ]
  },
  {
   "title": "Pooling Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "druid_pooling_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}",
     "legendFormat": "{{application}} {{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "druid_active_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}",
     "legendFormat": "{{application}} {{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Connection Pool Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logic Connect",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "increase(druid_logic_connect_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[1m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Logic Close",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "increase(druid_logic_close_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[1m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Logic Connect - Error",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "increase(druid_logic_connect_error_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[1m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Physical Connect",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "increase(druid_physical_connect_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[1m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Physical Close",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "increase(druid_physical_close_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[1m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Physical Connect - Error",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "increase(druid_physical_connect_error_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[1m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Pool Not Empty Wait count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "increase(druid_not_empty_wait_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[1m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    },
    {
     "title": "Pool Not Empty Wait Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(druid_not_empty_wait_millis{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m]) / rate(druid_not_empty_wait_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
       "legendFormat": "{{instance}} {{pool}}"
      }
     ]
    }
   ]
  },
  { "title": "SQL Execution Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "SQL Execution Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(druid_execute_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "SQL Execution Error",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(druid_error_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Start Transaction Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(druid_start_transaction_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Commit Transaction Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(druid_commit_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Roolback Transaction Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(druid_rollback_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  { "title": "SQL Execution Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Prepared Statement Open Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(druid_prepared_statement_open_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m]))"
    }
   ]
  },
  {
   "title": "Prepared Statement Close Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(druid_prepared_statement_closed_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m]))"
    }
   ]
  },
  {
   "title": "PS Cache Hit Ratio",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(druid_ps_cache_hit_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])) / sum(irate(druid_ps_cache_access_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])) * 100"
    }
   ]
  },
  {
   "title": "SQL Query Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(druid_execute_query_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "SQL Update Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(druid_execute_update_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "SQL Batch Execution Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(druid_execute_batch_count{application=\"$application\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  }
 ]
}