{
 "title": "Minio",
 "description": "Minio Version: RELEASE.2020-01-16T22-40-29Z",
 "tags": [ "object-storage" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "集群名",
    "query": "label_values(minio_version_info{},job)"
   },
   {
    "name": "metrics_port",
    "label": "Minio 地址",
    "query": "label_values(minio_version_info{},instance)"
   },
   {
    "name": "interval",
    "label": "间隔时间",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Minio is a high performance distributed object storage server, designed for large-scale private cloud infrastructure. For more information, check out the docs.",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "content": "<img src=\"https://min.io/resources/img/logo/MINIO_wordmark.png\" style=\"height: 55px;\"></img>"
  },
  {
   "title": "集群已使用空间",
   "type": "singlestat",
   "description": "Total number of offline disks for current MinIO server instances",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(disk_storage_used)",
     "legendFormat": "Total number of offline disks for current MinIO server instances"
    }
   ]
  },
  {
   "title": "集群实例状态",
   "type": "graph",
   "description": "Number of total/offline disks for current MinIO server instances",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(minio_disks_offline)", "legendFormat": "Offline instance" },
    { "expr": "sum(minio_disks_total{})", "legendFormat": "Total instance" }
   ]
  },
  {
   "title": "硬盘使用率",
   "type": "graph",
   "description": "Storage space usage",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_storage_used{instance=\"$metrics_port\",job=\"$job\"} / disk_storage_total{instance=\"$metrics_port\",job=\"$job\"} * 100",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "集群总容量",
   "type": "singlestat",
   "description": "Total number of disks for current MinIO server instances",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(disk_storage_total)",
     "legendFormat": "Total number of disks for current MinIO server instances"
    }
   ]
  },
  {
   "title": "集群内部节点数据传输(B/s)",
   "type": "graph",
   "description": "Data sent by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(internode_tx_bytes_total{instance=\"$metrics_port\"}[$interval])",
     "legendFormat": "传输字节数:"
    },
    {
     "expr": "rate(internode_rx_bytes_total{instance=\"$metrics_port\"}[$interval])",
     "legendFormat": "接收字节数:"
    }
   ]
  },
  {
   "title": "S3数据输入/输出(KB/s)",
   "type": "graph",
   "description": "Data received x transmited by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(s3_rx_bytes_total{instance=\"$metrics_port\"}[$interval])",
     "legendFormat": "Received: "
    },
    {
     "expr": "rate(s3_tx_bytes_total{instance=\"$metrics_port\"}[$interval])",
     "legendFormat": "Transmited:"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "graph",
   "description": "Total user and system CPU time spent in seconds",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$metrics_port\"}[$interval])",
     "legendFormat": "Total CPU {{instance}}"
    }
   ]
  },
  {
   "title": "S3接口总请求",
   "type": "graph",
   "description": "Data received by current Minio server instance",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_requests_total{instance=\"172.16.62.150:9000\",job=\"minio-metrics\"}) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "S3接口当前总请求数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_requests_current{instance=\"$metrics_port\",job=\"$job\"}) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "S3接口总错误请求数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_errors_total{instance=\"$metrics_port\",job=\"$job\"}) by (api)",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "sum(s3_requests_current{instance=\"$metrics_port\",job=\"$job\"}) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "S3接口延迟统计",
   "type": "graph",
   "description": "The current aggregate time spent servicing all HTTP requests  in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "s3_ttfb_seconds_sum{instance=\"$metrics_port\",job=\"$job\"}",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "HTTP请求状态",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(promhttp_metric_handler_requests_total{job=\"$job\",instance=\"$metrics_port\"}) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}